<x-app-main>
    <x-item 
        :codigo="$informe->codigo" 
        :image="$informe->ruta" 
        :title="$informe->nombre" 
        :resumen="$informe->resumen" 
        :autores="$informe->autores" 
        :acceso="$informe->tipo_acceso"
    />
</x-app-main>
